### ISSUE TITLE
There is a suspected mistake in metric.py of Track2.

### ISSUE THREAD

**Issue by FunnyDragonK** [SereTOD/SereTOD-2022#17]
https://github.com/SereTOD/SereTOD2022/blob/3f6759a7fba734955f0bf92453dfe0e172dbb732/Track2/baseline/metrics.py#L110

I think it should be modified here to 'for si in true_si.split(','):'

**Comment by Red-Liu199** [comment]
Thanks for your correction. The original evaluation script underestimated the recall of system intention. We have corrected the metrics.py and the results of baseline model.

**Comment by SereTOD** [comment]
Thanks for your correction. The original evaluation script underestimated the recall of system intent. We have corrected the metrics.py and the results of baseline model.
